name: flutter_app
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.0
  url_launcher: ^6.1.2
  english_words: ^4.0.0
  audioplayers: ^0.20.1
  rflutter_alert: ^2.0.4
  font_awesome_flutter: ^10.1.0
  back_button_interceptor: ^6.0.0
  geolocator: ^8.2.1
  http: ^0.13.4
  flutter_spinkit: ^5.1.0
  flutter_svg: ^1.1.1+1
  get: 4.6.3



#  simple_location_picker: ^0.0.3
#  lottie: ^1.3.0
#  flutter_icons: ^1.1.0
#  intl: ^0.16.1
#  google_fonts: ^3.0.1
#  flutter_custom_clippers: ^2.0.0

#  geocoder_offline: ^0.2.1
#  cities: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0


flutter:

  # The following adds the Material Design Icons font to your application.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/
     - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf
    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900
    - family: Cairo
      fonts:
        - asset: fonts/Cairo-Regular.ttf
          weight: 400
        - asset: fonts/Cairo-Bold.ttf
          weight: 700
